language: generic

jobs:
  include:
    - stage: a
      if: env(SDK) = a
      env:
        SDK: a
      script:
        - echo $SDK
     - stage: a
       if: env(SDK) = b
       env:
         SDK: b
       script:
         - echo $SDK

